### ISSUE TITLE
Callout Notifications

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#767] opened 2022-08-29 10:37 UTC
## Description
As a  User I want to know when a new Callout is creatd
As a Lead I want my users to know when I create one

## Acceptance criteria

- [ ] Should ‹testable condition that should be satisfied›
- [ ] …

**Comment by techsmyth** [comment] 2022-08-30 06:09
Duplicate of #136

**Closed as completed by techsmyth** 2022-08-30 06:09 UTC
