### ISSUE TITLE
BUG: Host of VC not clickable on profile

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1403] opened 2024-08-23 10:15 UTC
**Describe the bug**
On the VC profile the host is not clickable

**To Reproduce**
1. Go to a VC profile
2. Try to click on the host

**Expected behavior**
I want to go to the VC host profile

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bobbykolev** [comment] 2024-11-06 08:15
Closing as duplicate of: https://github.com/alkem-io/client-web/issues/6996

**Closed as completed by bobbykolev** 2024-11-06 08:15 UTC
Labels: bug, client
